### ISSUE TITLE
moodle's fix for "MSA-18-0020: Login CSRF vulnerability in login form" introduced a token

### ISSUE THREAD

**Issue by tailcat** [LafColITS/Moodle-auth_casattras#14]
The plugin needs to be updated to handle the login token, at the moment "$CFG->disablelogintoken = true" has to be set in moodle's config.php in order for logins to work.

**Comment by peterhuppertz** [comment]
The logintoken generation can be added ton auth.php. I create a pull request.

**Comment by nkokkos** [comment]
Hi,
if you add:
$frm->logintoken = \core\session\manager::get_login_token();
right after line 209: 
https://github.com/LafColITS/Moodle-auth_casattras/blob/master/auth.php#L209
you can login in with no problem.
