### ISSUE TITLE
missing 3rdpartylibs.xml file

### ISSUE THREAD

**Issue by danmarsden** [LafColITS/Moodle-auth_casattras#20]
When a plugin includes a 3rd party lib, it must also implement the thirdpartylibs.xml file to cover detials on the library that is included.
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

But.... Moodle core already includes the PHP CAS lib - and it includes it in a much cleaner way without the docs/extra files that aren't required.

Ideally I'd like to see your plugin use the cas lib already in core (which also appears to be more up to date than yours is) - and you would just add a dependency in your version.php like:
```
$plugin->dependencies = array(
    'auth_cas' => ANY_VERSION
);
```
more info on dependencies are here:
https://docs.moodle.org/dev/version.php

If you want to retain the cas lib (I'm hoping you don't) you will need to add the thirdpartylibs.xml file prior to approval in the plugins db.

**Comment by mackensen** [comment]
@danmarsden I'm guessing this is leftover from an era when core phpCAS didn't support attribute release. I don't see a reason to ship our own version.
