### ISSUE TITLE
legacy cas_form.html file

### ISSUE THREAD

**Issue by danmarsden** [LafColITS/Moodle-auth_casattras#22]
Looks like this dates back to when we had to drop the auth form into the html form - would be good to tidy this up at some point as having a mix of PHP and html code isn't good practice.

This doesn't block approval in the plugins db of course.

**Comment by mackensen** [comment]
The whole multi-authentication implementation (which we don't use ourselves) needs to be refactored along the lines of https://tracker.moodle.org/browse/MDL-60432.
