### ISSUE TITLE
favicon not working

### ISSUE THREAD

**Issue by sparse91** [LafColITS/Moodle-auth_casattras#30]
Hello
I upload a png favicon for CAS button and favicon is not showing. I get 404 error in browser inspect:
https://moodleaddress/pluginfile.php/1/auth_casattras/logo/ 404

I tested in both 3.6 and 3.9 version of Moodle.

**Comment by mackensen** [comment]
This was fixed by #31 and will be released shortly.

**Comment by mackensen** [comment]
Fixed in v3.7.2.
