### ISSUE TITLE
v3.7.2 | Moodle 3.9 | PHP 7.3

### ISSUE THREAD

**Issue by gemguardian** [LafColITS/Moodle-auth_casattras#32]
We got an question regarding this plugin.

We tried to map CAS fields to Moodle custom profile fields, but it does not seem to be able to map the information correctly. We can see that the data is being send. When we pick a Moodle standard field it is being mapped. 

Is there something we are missing?

**Comment by mackensen** [comment]
@gemguardian is the custom field set to be updated on creation, or on every login?

**Comment by gemguardian** [comment]
Updated on creation

- We have decided not to move forward with this plugin and use the OATH2
