### ISSUE TITLE
Watch for MDL-50448 for the changes in the settings storage

### ISSUE THREAD

**Issue by mudrd8mz** [LafColITS/Moodle-auth_casattras#4]
In your code, you follow the legacy way of storing plugin configuration by using the plugin name as `auth/casattras` in `set_config()` calls. This convention has been replaced by so called frankenstyle (https://docs.moodle.org/dev/Frankenstyle). In the Moodle tracker issue MDL-50448 there is a discussion on how this should be normalized in the future. You may want to watch that issue to be up-to-date with the upstream development.

**Comment by adamfranco** [comment]
Hi @mudrd8mz, thanks for the report and description of the issue. My institution has stopped using Moodle, so I no longer have time to devote to this plugin. I'd be happy to review and merge a pull request if you get it working.

**Comment by mackensen** [comment]
I'm working on this right now; for the most part the changes are straightforward. The cas/casattras conversion tool might need to live somewhere else.
