### ISSUE TITLE
source/CAS/client.php->_readURL() ignores $this->_no_cas_server_validation

### ISSUE THREAD

**Issue by heyrex** [LafColITS/Moodle-auth_casattras#7]
I was unable to make this plugin work in a development environment that has no SSL certs. The option to ignore the certificate was not honored and after running through with a real-time debugger I found that the problem was solved by adding the following code to line 2420 of source/CAS/client.php:

```php
        if($this->_no_cas_server_validation){
        	$this->_curl_options[CURLOPT_SSL_VERIFYHOST] = false;
        	$this->_curl_options[CURLOPT_SSL_VERIFYPEER] = false;
        }
```

I also noted that this problem has been reported on a few different forms by admins who were not programmers and were unable to figure out what the failure was.

The above fix might not be the optimal location to patch but it certainly resolved the issue for me.

Will also report to the upstream cas auth repo.

**Comment by heyrex** [comment]
This may be related to:
https://tracker.moodle.org/browse/MDL-36818

**Comment by adamfranco** [comment]
Thanks for this report, I've just pushed a new 2017011900 release with an updated version of phpCAS. Please give it a try and report back if you are still having difficulties.
