### ISSUE TITLE
Does it work on Moodle 3.3

### ISSUE THREAD

**Issue by ebarra** [LafColITS/Moodle-auth_casattras#9]
I am using this awesome plugin in Moodle 2.9 but now I am trying to use it in Moodle 3.3 and it does not let users login with the CAS server.
Does anyone know if it works on Moodle 3.3?

Thank you
Enrique

**Comment by mackensen** [comment]
I haven't tried yet, but I imagine it's broken because of #4.

**Comment by mackensen** [comment]
I'm running the existing version of the plugin on Moodle 3.3.1 and CAS authentication appears to be working, though it throws notices about #4.

**Comment by azito122** [comment]
Moodle 3.3 is no longer supported.
